#!/bin/sh
# depends on: groff, gnu eqn, less
: -e
usage() {
	echo "usage: man [section] name"
}
mandirs="/usr/share/man /usr/local/share/man /data/data/com.termux/files/usr/share/man"

runman() {
	name="$2"
	section="$1"
	manpath="/usr/share/man/man$section/$name.$section"
	cat "$manpath" | eqn - | groff -mandoc -Tutf8 | less
}

if [ "$#" = 2 ]; then
	case "$1" in
	1|2|3|4|5|6|7|8)
		runman "$1" "$2"
		;;
	*)
		usage
		exit 1
	esac
elif [ "$#" = 1 ]; then
	name="$1"
	for i in 1 2 3 4 5 6 7 8; do
	  for mandir in $mandirs; do
	        if [ -f "$mandir/man$i/$name.$i" ]; then
		        section="$i"
		    else
		        echo "not found - $mandir/man$i/$name.$i"
	        fi
	    done
	done
	if [ -z "$section" ]; then
		echo "man: No entry for $1 in the manual."
		exit 1
	fi
	runman "$section" "$name"
else
	usage
	exit 1
fi
